language: html, js, css
html:
  - "5"

services:
  
# command to install dependencies
install:

# command to run tests
before_script:

script:
  - js
branches:
  only:
  
  - kamar_diary
  - master
after_success:
  
env:

  - 'index.html'